/*INSERT - Tabela Bairros*/
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Água Rasa',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Alto Da Mooca',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Aricanduva',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Artur Alvim',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Bairro do Limoeiro',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Bairro do Palanque',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Bairro Dos Pereira',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Barro Branco',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Belém',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Belenzinho',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Burgo Paulista',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cangaíba',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Capão do Embira',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Carrãozinho',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Catumbi',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Chácara Belenzinho',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('ChÁcara Califórnia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Chácara Califórnia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Chácara Cruzeiro do Sul',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Chácara da Penha',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Chácara da Vovó Luiza',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Chácara do Piqueri',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Chácara Dona Olívia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Chácara Figueira Grande',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Chácara Mafalda',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Chácara Maranhão',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Chácara Paraíso',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Chácara Santo Antonio',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Chácara Santo Antônio',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Chácara São Marcos',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Chácara Seis de Outubro',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Chácara Tatuapé',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cidade A.E.Carvalho',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cidade Castro Alves',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cidade Centenário',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cidade Continental',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cidade Kemel',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cidade Líder',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cidade Mãe do Ceu',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cidade Nitro Operária',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cidade Nova São Miguel',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cidade Patriarca',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cidade Popular',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cidade Quarto Centenário',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cidade São Mateus',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cidade São Miguel',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cidade Satélite Santa Barbara',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cidade Tiradentes',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cj Hab Cintra Gordinho',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cj Hab Juscelino Kubitschek',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cj Res Oratório 2',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cohab Fazenda do Carmo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cohab Guaianases',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cohab Iva Santa Etelvina',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cohab Santa Etelvina 1 B',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cohab Santa Etelvina 1A',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cohab Santa Etelvina 2 A',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cohab Santa Etelvina 2 B',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cohab Santa Etelvina 3 A',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cohab Santa Etelvina 4',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cohab Santa Etelvina 5 A',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cohab Santa Etelvina 6 A',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cohab Santa Etelvina 7',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cohab São Carlos',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cohab São Miguel',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cohab Sítio Conceição',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cohab Vila Progresso 1',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cohab Vila Progresso 2',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cohab Vila Silvia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Cojunto Habitacional Cidade Tiradentes',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Araucária',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto dos Pinheiros',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Esmeralda',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Habitacional A.E. Carvalho',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Habitacional Águia De Haia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Habitacional Baltazar',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Habitacional Barreira Grande',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Habitacional Barro Branco 2',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Habitacional Camilópolis',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Habitacional Dom Joao Nery',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Habitacional Encosta Norte',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Habitacional Fazenda Guaianases A/B',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Habitacional Fazenda Itaim',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Habitacional Fazenda Juta',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Habitacional Gleba do Pêssego',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Habitacional Hospital Itaquera',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Habitacional Inácio Monteiro',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Habitacional Itaim Paulista',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Habitacional Itaquera 4',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Habitacional Jardim Mabel',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Habitacional Jardim Sao Francisco',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Habitacional José Bonifácio',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Habitacional Juta',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Habitacional Limoeiro',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Habitacional Mal Mascarenhas De Moraes',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Habitacional Marechal Tito',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Habitacional Nazaré',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Habitacional Padre Jose De Anchieta',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Habitacional Padre Manuel De Paiva',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Habitacional Santa Etelvina Barro Branco 1',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Habitacional Vila Conceição',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Perola',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Promorar Rio Claro',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Promorar Sapopemba',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Residencial (Ant. Bairro F. Lima) Prestes Maia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Residencial Gonzaga',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Residencial Padre Manuel Da Nobrega',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Residencial Prestes Maia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Conjunto Residencial Teotônio Vilela',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Engenheiro Goulart',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Engenheiro Trindade',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Ermelino Matarazzo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Fazenda Aricanduva',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Fazenda Caguaçu',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Fazenda do Carmo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Fazenda Itaim',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Fazenda Nossa Senhora do Carmo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Guaianases',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Guaiauna',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Hipódromo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Iguatemi',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Itaim Paulista',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Itaquera',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Adelaide',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Adutora',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Aidar',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Aimoré',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Alto Alegre',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Alto Pedroso',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Amaro',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim America da Penha',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Ana Rosa',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Anália Franco',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Ângela',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Aricanduva',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Arizona',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Artur Alvim',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Assunção',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Augusto',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Aurora',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Avelino',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Bartira',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Beatriz',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Belém',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Benfica',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Brasil',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Brasília',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Brigida',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Buriti',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Caguacú',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Camargo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Campos',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Cangaíba',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Cardoso',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Carolina',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Catarina',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Célia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Centenário',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Cibele',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Cinco de Julho',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Cisper',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Clara Regina',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Cleide',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Coimbra',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Colorado',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Concórdia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Conquista',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Cotching',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Cotinha',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim da Casa Pintada',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim da Figueira',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Da Figueira',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Dalmo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Danfer',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim das Camélias',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim das Carmelitas',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim das Laranjeiras',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim das Oliveiras',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim das Rosas',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim de Lorenzo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Dias',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Divino',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim do Campo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim do Castelo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim do Norte',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Dona Sinha',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim dos Ipês',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Egle',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Elba',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Elian',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Eliane',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Elsa',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Ester',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Etelvina',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Eva',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Fernandes',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Flavio',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Fluminense',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Fonte São Miguel',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Galli',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Gianetti',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Gondolo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Gonzaga',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Grimaldi',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Guaianases',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Guairacá',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Guanabara',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Guannan',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Guiomar',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Haddad',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Haia Do Carrao',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Helena',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Heloisa',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Hercília',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Iara',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Iguaçu',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Iguatemi',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Imperador',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Indaia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Independência',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Ipanema',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Irene',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Itália',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Itamarati',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Itapema',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Itapemirim',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Itapólis',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Iva',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Ivete',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Ivone',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Janilópolis',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Jaraguá',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Jaú',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Jordão',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Lageado',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Laone',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Lapema',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Laranjal',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Laura',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Liderança',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Limoeiro',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Lisboa',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Lourdes',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Lourenço',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Luciana',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Lucinda',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Luzitano',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Mabel',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Maia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Marabá',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Maria Lidia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Maria Lídia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Maria Luiza',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Marilia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Marilu',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Marina',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Maringá',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Marpu',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Matarazzo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Meliunas',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Metropolitano',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Miami',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Mimar',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Miragaia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Miriam',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Moreno',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Morganti',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Nair',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Nalice',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Nazareth',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Nélia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Nice',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Nicolau',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Noêmia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Nordeste',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Norma',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Nossa Senhora do Carmo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Nova Carrão',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Nove De Julho',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Olímpia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Otília',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Panorama',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Paraguaçu',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Paula',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Paulistânia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Pedra Branca',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Pedro Jose Nunes',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Penha',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Piquerobi',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Piratininga',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Planalto',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Ponte Rasa',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Popular',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Porteira Grande',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Progresso',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Quisisana',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Record',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Recreio',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Redenção',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Redil',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Ricardo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Robru',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Rodolfo Pirani',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Romano',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Roseli',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Rosicler',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Rosina',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Ruth',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Samara',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Santa Adélia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Santa Marcelina',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Santa Margarida',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Santa Maria',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Santa Rita',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Santa Terezinha',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Santana',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Santo André',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Santo Antonio',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Santo Eduardo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Santo Elias',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Santo Onofre',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim São Benedito',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim São Carlos',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim São Cristóvão',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim São Francisco',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim São Gonçalo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim São Joao',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim São Jose',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim São Lourenço',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim São Luis',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim São Martinho',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim São Nicolau',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim São Paulo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim São Pedro',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim São Roberto',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim São Sebastião',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim São Vicente',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Sapopemba',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Senice',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Silva Teles',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Silveira',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Silvia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Soares',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Sofia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Soraia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Tango',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Tereza',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Têxtil',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Textilia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Thealia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Théalia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Tietê',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Três Marias',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Triana',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Tua',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Ubirajara',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Valquíria',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Vera Cruz',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Verônia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Vila Carrão',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Vila Formosa',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Vilma Flor',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Jardim Virginia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Lageado',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Lar Nacional',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Mooca',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parada Quinze',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Andre Pereira',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Artur Alvim',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Bancário',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Bela Vista',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Boa Esperança',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Boturussu',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Central',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Colonial',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Cruzeiro do Sul',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque da Mooca',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Das Paineiras',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque do Carmo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Dom Joao Nery',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Eduardo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Guarani',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Guedes',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Industrial',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Líbano',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Luiz Mucciolo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Maria Luiza',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Paulistano',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Real',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Residencial Dabril',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Santa Amélia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Santa Madalena',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Santa Rita',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Santo Antônio',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque São Jorge',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque São Lourenço',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Sao Lucas',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque São Rafael',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Savoy City',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Sevilha',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Sônia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Tomas Saraiva',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Parque Vila Prudente',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Passagem Funda',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Penha',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Penha de França',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Ponte Rasa',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Pq Resesidencial Oratório',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Profilurb Pêssego',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Quarta Parada',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Quinta Da Paineira',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Recanto Alegre',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Recanto Verde Do Sol',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Roseira',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Santa Etelvina',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('São Miguel Paulista',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Sapopemba',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Sítio do Palanque',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Sitio dos Francas',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Sitio Pinheirinho',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Sitio São João',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Tatuapé',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Terceira Divisão',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Abc',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Aimoré',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Alabama',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Alois',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Alpina',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Alto da Boa Vista',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Alzira',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Amadeu',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Americana',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Ana Clara',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Anadir',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Andes',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Angelina',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Antenor',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Antonieta',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Antonina',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Aparecida',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Araci',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Araguaia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Aricanduva',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Arisi',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Arlindo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Áurea',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Azevedo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Bancaria',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Barbosa',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Barreira Grande',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Bauab',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Beatriz',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Bela',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Bela Vista',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Belo Horizonte',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Bertioga',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Bozzini',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Brasil',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Buenos Aires',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Caju',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Califórnia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Campanela',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Canero',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Cardoso Franco',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Carlos de Campos',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Carmem',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Carmosina',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Carolina',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Carrão',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Celeste',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Centenário',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Central',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Chabilândia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Charlot',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Chavantes',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Clara',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Claudia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Cleonice',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Clotilde',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Conceição',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Constança',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Corberi',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Cosmopolita',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Costa Melo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Cruzeiro',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Cunha Bueno',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Curuçá',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Da Imprensa',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Dalila',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Danúbio Azul',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Darli',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Diva',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Divina Pastora',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Dom Duarte Leopoldo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Domitila',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Doutor Eiras',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Else',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Ema',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Embira',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Escolar',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Esperança',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Ester',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Eugenia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Eugênio',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Eutália',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Falconi',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Fátima',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Feliz',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Fernandes',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Fernando',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Fidelis Ribeiro',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Florinda',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Formosa',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Franci',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Frugolli',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Germaine',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Gertrudes',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Gil',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Giordano',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Gomes Cardim',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Graciosa',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Granada',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Guarani',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Guilhermina',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Gustavo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Haddad',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Heloisa',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Hilda',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila I.V.G.',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Iguaçu',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Industrial',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Invernada',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Iolanda',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Iraci',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Itaim',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Itaquera de Baixo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Ivone',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Jacuí',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Jose Moreira',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Julio',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Jurema',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Lais',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Lavinia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Leme',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Libanesa',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Londrina',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Lourdes',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Lúcia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Lúcia Elvira',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Luisa',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Luso Brasileira',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Luzimar',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Luzitana',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Macedópolis',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Mafra',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Maluf',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Margareth',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Margarida',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Maria Amália',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Marieta',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Marilena',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Matias',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Matilde',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Mauad',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Melo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Mendes',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Mercedes',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Merly',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Mesquita',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Minerva',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Mirim',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Mirtes',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Moca',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Moderna',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Monte Santo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Montevideo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Moreira',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Morgadouro',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Nair',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Nancy',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Naufal',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Néila',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Nhocuné',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Norma',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Nova',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Nova Curuca',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Nova Granada',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Nova Itaquera de Baixo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Nova Manchester',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Nova Paulicéia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Nova Savoia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Nova Utinga',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Nova York',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Odete',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Olinda',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Olívia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Oratório',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Orlando',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Palma',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Paraguassu',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Paranaguá',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Paulina',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Paulista',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Paulo Silas',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Pedroso',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Penteado',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Pierina',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Piracicaba',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Popular',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Portuguesa',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Praia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Prima',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Primavera',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Princesa Isabel',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Progresso',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Prudente',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Raquel',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Ré',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Regente Feijó',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Regina',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Reis',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Renato',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Ribeiro dos Santos',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Rica',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Rio Branco',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Robertina',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Rosa',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Rosaria',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Rufino',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Rui Barbosa',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Salete',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Sampaio',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Santa Clara',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Santa Cruz',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Santa Inês',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Santa Isabel',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Santa Lúcia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Santa Rita',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Santa Tereza',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Santa Terezinha',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Santa Virginia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Santana',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Santo Antonio',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Santo Estevam',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Santo Henrique',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila São Domingos',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila São Francisco',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila São Geraldo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila São Jorge',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila São Jose',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila São José',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila São Mauricio',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila São Nicolau',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila São Paulo',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila São Silvestre',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila São Vicente',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Sara',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Sartori',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Seabra',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Sergio',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Silvia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Simone',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Sinha',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Siqueira',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Sirene',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Síria',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Solange',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Stela',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Suíça',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Talarico',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Taquari',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Tolstói',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Toni',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila União',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Valdemar',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Vera',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Verde',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Vidal',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Virginia',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Vitoria',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Xavantes',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Zefira',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Zelina',1);
INSERT INTO Bairros (nomeBairro, idMunicipio) values ('Vila Zilda',1);